version: '3.5'

networks:
  prod:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  nginx:
    hostname: nginx
    build:
      context: ./docker/nginx
      dockerfile: ./prod.Dockerfile
    networks:
      prod:
        ipv4_address: 10.1.0.10
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./docker/nginx/prod.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/prod.conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/common.conf.d:/etc/nginx/common.conf.d:ro
      - ./docker/.volumes/letsencrypt:/etc/letsencrypt
      - ./docker/.volumes/certbot-webroot:/var/www/certbot:ro
    restart: always

  letsencrypt:
    hostname: letsencrypt
    build:
      context: ./docker/letsencrypt
      dockerfile: ./prod.Dockerfile
    env_file: ./docker/letsencrypt/.env.production.local
    networks:
      prod:
        ipv4_address: 10.1.0.99
    volumes:
      - ./docker/.volumes/letsencrypt:/etc/letsencrypt
      - ./docker/.volumes/certbot-webroot:/certbot-webroot
    restart: 'no'
